In [1]:
import numpy as np

In [3]:
arr  = np.array([1,2,3,4])

In [5]:
arr

array([1, 2, 3, 4])

In [15]:
# Creating an zero filled np array
arr = np.zeros((3,4))

In [17]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# Creating an one filled np array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# Creating an number(choise) filled np array
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [31]:
# generating an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
np.linspace(1,100,5) #evenly spaced

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [49]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [51]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
myarr.shape

(4, 3)

In [59]:
myarr.size

12

In [61]:
myarr.ndim

2

In [89]:
myarr.dtype

dtype('int64')

In [91]:
myarr.astype(np.int32)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [93]:
reshape = myarr.reshape((3,4))

In [95]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])