In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [82]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [86]:
flat[0]

1

In [88]:
flat[:5]

array([1, 2, 3, 4, 5])

In [90]:
flat[::2] #every 2 nd element

array([ 1,  3,  5,  7,  9, 11])

In [92]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [104]:
b = flat[3:7].copy() #this is copy if i make this then changes will not affect the original array

In [96]:
b

array([4, 5, 6, 7])

In [98]:
b[2] = 444

In [100]:
b

array([  4,   5, 444,   7])

In [102]:
flat #this is because slicing returns the view not a copy Changes affect the original array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
arr = np.array([1,54,23,45,6,7,8,77])

In [110]:
arr[[1,3,5]] #fancy indexing

array([54, 45,  7])

In [115]:
arr[arr>10] #boolean masking

array([54, 23, 45, 77])

In [117]:
# Exercises for Practice
# • Create a 3×3 array filled with random numbers and print its shape.
# • Convert an array of floats [1.1, 2.2, 3.3] into integers.
# • Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6] .
# • Reshape a 1D array of size 9 into a 3x3 matrix.
# • Use boolean masking to filter numbers greater than 50 in an array.

In [139]:
import random
arr = np.random.randint(1, 101, size=(3, 3)) #Q1

In [141]:
arr


array([[48, 60, 36],
       [27, 78, 10],
       [38, 22, 83]])

In [203]:
arr = np.array([1.1,2.2,3.3])

In [213]:
integer_arr = arr.astype(int) #Q2

In [215]:
integer_arr

array([1, 2, 3])

In [224]:
arr = np.array([1,2,3,4,5,6]) 
arr[[0,2,4]] #Q3

array([1, 3, 5])

In [230]:
arr = np.ones(9,dtype=int)

In [232]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [234]:
arr.reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [274]:
arr = np.random.randint(1,101,size = (3,3))

In [276]:
arr[arr>50]

array([73, 84, 67, 70, 69, 86])