In [5]:
import numpy as np 
arr = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

In [7]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.sum(arr,axis=0) #axis = 0 means from row from top to down

array([22, 26, 30])

In [13]:
np.sum(arr,axis=1) #axis = 1 means from col from left to right


array([ 6, 15, 24, 33])

In [15]:
arr[0][1]

2

In [19]:
arr[0,1] #first argument row second column

2

In [29]:
# Multidimensional indexing
arr[0:2,1:3] #orws from 0 to 2 means 0 and 1  and col from 1 to 3 means col 1 and col 2

array([[2, 3],
       [5, 6]])

In [37]:
# Indexing in 3d arrays
arr3D = np.array([ [[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]
                  ])

In [41]:
arr3D.shape #(depth,rows,columns)


(2, 2, 3)

In [45]:
arr3D[0,1,2] #first sheet second row third column

6

In [55]:
arr3D[:,0,:] #get the first row from both sheet  ":" this means considering all

array([[1, 2, 3],
       [7, 8, 9]])

In [58]:
arr3D[:,0,:] = 0

In [60]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])